In [15]:
pip install transformers

In [4]:
from transformers import pipeline
import transformers
import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2ForCTC,Wav2Vec2Tokenizer
import numpy as np
import transformers

In [3]:
print(transformers.__version__)

4.57.3


In [6]:
import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2ForCTC,Wav2Vec2Tokenizer
import numpy as np

In [7]:
tokenizer=Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model=Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [14]:
audio,sampling_rate = librosa.load('speech.wav',sr=16000)
audio,sampling_rate

(array([ 0.        ,  0.        ,  0.        , ..., -0.0167081 ,
         0.00231273, -0.00143074], dtype=float32),
 16000)

In [17]:
display.Audio('speech.wav',autoplay=True)

In [18]:
input_values=tokenizer(audio,return_tensors="pt").input_values
input_values

tensor([[ 0.0003,  0.0003,  0.0003,  ..., -0.2073,  0.0290, -0.0175]])

In [19]:
logits= model(input_values).logits
logits

tensor([[[ 13.4362, -26.1836, -25.8760,  ...,  -5.9702,  -6.2677,  -7.2624],
         [ 13.5408, -26.2885, -25.9783,  ...,  -6.0059,  -6.3052,  -7.2813],
         [ 13.6466, -26.3888, -26.0761,  ...,  -6.0360,  -6.3513,  -7.2886],
         ...,
         [ 12.5584, -25.9320, -25.6298,  ...,  -6.0833,  -6.5770,  -7.0673],
         [ 12.6933, -25.9360, -25.6428,  ...,  -6.1593,  -6.7100,  -7.1177],
         [ 12.7740, -25.9669, -25.6772,  ...,  -6.1795,  -6.7548,  -7.1534]]],
       grad_fn=<ViewBackward0>)

In [20]:
predicted_ids=torch.argmax(logits,dim=-1)
predicted_ids

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0, 21,  8,  8,  0,  0,  8, 14,  4,  4, 17,  0,  0,  8,
          0, 13,  0,  9,  0, 10,  9,  9, 21,  0,  4,  4,  0,  0,  5,  0, 25,  0,
         13,  0,  0, 10,  0,  0, 25,  0,  0,  0,  8,  0,  9,  0,  0,  0,  4,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  6, 11,  0,  0,  0, 10,  0, 12,  0,  4,  4,  0,  0, 10, 12,
         12,  4,  4,  4,  4,  7,  4,  4,  0, 12,  0,  0,  0,  0,  7, 17,  0,  0,
          0, 23,  0,  0,  0, 15,  0,  5,  0,  4,  4,  0,  0,  0,  0,  7, 16,  0,
          0,  0, 14,  0, 10,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  4,  4,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,

In [23]:
transciptions=tokenizer.decode(predicted_ids[0])
transciptions

'GOOD MORNING EVRIVON THIS IS A SAMPLE AUDIO'